const TECHNIQUES = {
    qi_gathering: { id: "qi_gathering", name: "Qi Gathering", tier: "basic", power: 1.0, cooldown: 0, effect: null },
    fist_strike: { id: "fist_strike", name: "Fist Strike", tier: "basic", power: 0.8, cooldown: 0, effect: "ignore_defense_20" },

    wind_slash: { id: "wind_slash", name: "Wind Slash", tier: "common", power: 1.2, cooldown: 1, effect: "crit_10" },
    sneak_attack: { id: "sneak_attack", name: "Sneak Attack", tier: "common", power: 1.3, cooldown: 1, effect: "ignore_defense_40" },
    pill_refining: { id: "pill_refining", name: "Pill Refining", tier: "common", power: 0, cooldown: 1, effect: "heal_25" },
    iron_body: { id: "iron_body", name: "Iron Body", tier: "common", power: 0, cooldown: 1, effect: "defend_60" },
    qi_shield: { id: "qi_shield", name: "Qi Shield", tier: "common", power: 0, cooldown: 1, effect: "negate_next_hit" },
    meridian_cleanse: { id: "meridian_cleanse", name: "Meridian Cleanse", tier: "common", power: 0, cooldown: 1, effect: "cleanse_heal_10" },

    clan_hidden_art: { id: "clan_hidden_art", name: "Clan Hidden Art", tier: "uncommon", power: 1.8, cooldown: 2, effect: "heal_15" },
    flame_strike: { id: "flame_strike", name: "Flame Strike", tier: "uncommon", power: 1.5, cooldown: 2, effect: "burn" },
    frost_wave: { id: "frost_wave", name: "Frost Wave", tier: "uncommon", power: 1.2, cooldown: 2, effect: "reduce_atk_20" },
    lightning_step: { id: "lightning_step", name: "Lightning Step", tier: "uncommon", power: 1.0, cooldown: 2, effect: "dodge_next" },
    stone_fist: { id: "stone_fist", name: "Stone Fist", tier: "uncommon", power: 1.6, cooldown: 2, effect: "stun" },
    qi_drain: { id: "qi_drain", name: "Qi Drain", tier: "uncommon", power: 1.0, cooldown: 2, effect: "steal_qi_15" },

    seven_star_sword: { id: "seven_star_sword", name: "Seven Star Sword", tier: "rare", power: 2.0, cooldown: 3, effect: "pure_damage" },
    blood_blossom: { id: "blood_blossom", name: "Blood Blossom", tier: "rare", power: 0, cooldown: 3, effect: "missing_hp_damage" },
    soul_transference: { id: "soul_transference", name: "Soul Transference", tier: "rare", power: 0, cooldown: 3, effect: "steal_hp_20" },
    qi_burst: { id: "qi_burst", name: "Qi Burst", tier: "rare", power: 2.5, cooldown: 3, effect: "consume_half_qi" },
    phantom_step: { id: "phantom_step", name: "Phantom Step", tier: "rare", power: 1.0, cooldown: 3, effect: "dodge_counter" },
    earth_prison: { id: "earth_prison", name: "Earth Prison", tier: "rare", power: 0.5, cooldown: 3, effect: "skip_enemy_turn" },

    heaven_defying_palm: { id: "heaven_defying_palm", name: "Heaven-Defying Palm", tier: "legendary", power: 3.0, cooldown: 4, effect: "ignore_defense_100" },
    sword_domain: { id: "sword_domain", name: "Sword Domain", tier: "legendary", power: 0, cooldown: 4, effect: "dot_3turns" },
    flame_domain: { id: "flame_domain", name: "Flame Domain", tier: "legendary", power: 0, cooldown: 4, effect: "burn_block_heal" },
    void_severance: { id: "void_severance", name: "Void Severance", tier: "legendary", power: 0, cooldown: 4, effect: "missing_hp_150" },
    celestial_tribulation: { id: "celestial_tribulation", name: "Celestial Tribulation", tier: "legendary", power: 4.0, cooldown: 4, effect: "sacrifice_30" },

    soul_banner: { id: "soul_banner", name: "Soul Banner", tier: "mythical", power: 0, cooldown: 4, effect: "soul_banner_attack" },
    heaven_defying_domain: { id: "heaven_defying_domain", name: "Heaven-Defying Domain", tier: "mythical", power: 0, cooldown: 5, effect: "slow_time" },
    sundered_night: { id: "sundered_night", name: "Sundered Night", tier: "mythical", power: 3.5, cooldown: 5, effect: "ignore_defense_80" },
    underworld_river: { id: "underworld_river", name: "Underworld River", tier: "mythical", power: 0, cooldown: 4, effect: "hp_drain_20" },
    flowing_time: { id: "flowing_time", name: "Flowing Time", tier: "mythical", power: 0, cooldown: 6, effect: "reset_cooldowns" },
    karma_severance: { id: "karma_severance", name: "Karma Severance", tier: "mythical", power: 0, cooldown: 4, effect: "reduce_enemy_damage_50" },
    ancient_god_transformation: { id: "ancient_god_transformation", name: "Ancient God Transformation", tier: "mythical", power: 2.0, cooldown: 3, effect: "stun_plus_buff" },
    slaughter_domain: { id: "slaughter_domain", name: "Slaughter Domain", tier: "mythical", power: 0, cooldown: 0, effect: "passive_damage_per_kill" },
    rebirth_art: { id: "rebirth_art", name: "Rebirth Art", tier: "mythical", power: 0, cooldown: 99, effect: "full_heal_once" },
};

const ENEMY_TECHNIQUES = {
    claw_swipe: { name: "Claw Swipe", power: 1.0, type: "physical" },
    charge: { name: "Charge", power: 1.8, type: "physical", desc: "winds up a powerful charge" },
    poison_bite: { name: "Poison Bite", power: 1.2, type: "physical", effect: "poison" },
    healing_roots: { name: "Healing Roots", power: 0, type: "heal", healPct: 0.2 },
    dirty_strike: { name: "Dirty Strike", power: 1.1, type: "physical", effect: "reduce_atk" },
    sword_strike: { name: "Sword Strike", power: 1.3, type: "physical" },
    sect_strike: { name: "Sect Strike", power: 1.2, type: "physical" },
    qi_barrier: { name: "Qi Barrier", power: 0, type: "defend", defMult: 2.0 },
    advanced_sect_strike: { name: "Advanced Sect Strike", power: 1.6, type: "physical" },
    dark_strike: { name: "Dark Strike", power: 1.4, type: "dark" },
    life_drain: { name: "Life Drain", power: 0.8, type: "dark", effect: "drain" },
    slam: { name: "Slam", power: 1.3, type: "physical" },
    blood_curse: { name: "Blood Curse", power: 1.5, type: "dark", effect: "curse" },
    aoe_strike: { name: "AoE Strike", power: 0.8, type: "physical" },
    soul_attack: { name: "Soul Attack", power: 1.8, type: "soul", effect: "ignore_defense" },
    head_flying_attack: { name: "Head Flying Attack", power: 2.5, type: "dark" },
    summon_minions: { name: "Summon Minions", power: 0, type: "summon" },
    domain_attack: { name: "Domain Attack", power: 2.0, type: "domain" },
    elder_domain: { name: "Elder Domain", power: 2.2, type: "domain" },
    sect_ultimate: { name: "Sect Ultimate", power: 2.8, type: "domain" },
    grand_domain: { name: "Grand Domain", power: 3.0, type: "domain" },
    heavenly_strike: { name: "Heavenly Strike", power: 3.5, type: "celestial" },
    rage_mode: { name: "Rage Mode", power: 2.5, type: "physical", effect: "enrage" },
    terra_stomp: { name: "Terra Stomp", power: 2.0, type: "physical", effect: "stun" },
    beast_roar: { name: "Beast Roar", power: 1.5, type: "sound", effect: "fear" },
    sage_domain: { name: "Sage Domain", power: 3.5, type: "domain" },
    void_attack: { name: "Void Attack", power: 3.0, type: "void", effect: "ignore_defense" },
    time_distortion: { name: "Time Distortion", power: 2.0, type: "time", effect: "slow" },
    god_stomp: { name: "God Stomp", power: 2.2, type: "physical" },
    ancient_barrier: { name: "Ancient Barrier", power: 0, type: "defend", defMult: 3.0 },
    drake_breath: { name: "Drake Breath", power: 3.0, type: "elemental" },
    sky_dive: { name: "Sky Dive", power: 2.5, type: "physical" },
    scale_shield: { name: "Scale Shield", power: 0, type: "defend", defMult: 2.5 },
};

module.exports = { TECHNIQUES, ENEMY_TECHNIQUES };
